name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11, 16, 17-ea]
    env:
      MCL: examples/mcl
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Markov Clustering
      run: make -C examples mcl
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
    - name: Check for Updates
      run: mvn -B versions:display-dependency-updates versions:display-plugin-updates
    - name: Build with Maven
      run: mvn -B package
    - name: Build with Maven (Shade)
      run: mvn -Dshade=true -B package
    - name: Build Javadoc
      run: mvn -B javadoc:javadoc
      if: matrix.java-version == '17-ea' && github.ref == 'refs/heads/master'
    - name: Upload Pages
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site/apidocs
      if: matrix.java-version == '17-ea' && github.ref == 'refs/heads/master'
  examples:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Markov Clustering
      run: make -C examples mcl
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dshade=true -B
    - name: Symlink watset.jar
      run: ln -sf $PWD/target/watset.jar examples/watset.jar
    - name: Run Examples
      run: make -C examples HardClustering FuzzyClustering EvaluateClustering CommandLine
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run ShellCheck
      run: bash -c 'shopt -s globstar nullglob; shellcheck **/*.{sh,ksh,bash}'
